total_time_ns = 6712432008
ksvd_pkg_rev = "e4bc33e"
total_allocated_bytes = 9736846432
time_ns = 0
n_calls = 0
allocated_bytes = 0

[inner_timers.ksvd_update]
total_time_ns = 6712432008
total_allocated_bytes = 9736846432
time_ns = 6712432008
n_calls = 1
allocated_bytes = 9736846432

    [inner_timers.ksvd_update.inner_timers."compute and copy tsvd"]
    total_time_ns = 0
    total_allocated_bytes = 0
    time_ns = 113928631
    n_calls = 191
    allocated_bytes = 176761312

        [inner_timers.ksvd_update.inner_timers."compute and copy tsvd".inner_timers]

    [inner_timers.ksvd_update.inner_timers."copy results"]
    total_time_ns = 2920186770
    total_allocated_bytes = 31224672
    time_ns = 2920186770
    n_calls = 24
    allocated_bytes = 31224672

        [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."~copy results~"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 149305
        n_calls = 24
        allocated_bytes = 1504

            [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."~copy results~".inner_timers]

        [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."copy D"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 1674547
        n_calls = 24
        allocated_bytes = 9216

            [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."copy D".inner_timers]

        [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."copy X"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 2918362918
        n_calls = 24
        allocated_bytes = 31213952

            [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."copy X".inner_timers]

    [inner_timers.ksvd_update.inner_timers."find nonzeros"]
    total_time_ns = 0
    total_allocated_bytes = 0
    time_ns = 436423521
    n_calls = 191
    allocated_bytes = 754430976

        [inner_timers.ksvd_update.inner_timers."find nonzeros".inner_timers]

    [inner_timers.ksvd_update.inner_timers."maybe init bufers"]
    total_time_ns = 0
    total_allocated_bytes = 0
    time_ns = 9298
    n_calls = 1
    allocated_bytes = 16

        [inner_timers.ksvd_update.inner_timers."maybe init bufers".inner_timers]

    [inner_timers.ksvd_update.inner_timers."~ksvd_update~"]
    total_time_ns = 0
    total_allocated_bytes = 0
    time_ns = 180813469
    n_calls = 1
    allocated_bytes = 65862880

        [inner_timers.ksvd_update.inner_timers."~ksvd_update~".inner_timers]

    [inner_timers.ksvd_update.inner_timers."copy X"]
    total_time_ns = 0
    total_allocated_bytes = 0
    time_ns = 7797365
    n_calls = 1
    allocated_bytes = 24825200

        [inner_timers.ksvd_update.inner_timers."copy X".inner_timers]

    [inner_timers.ksvd_update.inner_timers."compute E_Ω"]
    total_time_ns = 3053272954
    total_allocated_bytes = 8683741376
    time_ns = 3053272954
    n_calls = 191
    allocated_bytes = 8683741376

        [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."copy data"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 343995986
        n_calls = 191
        allocated_bytes = 339296960

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."copy data".inner_timers]

        [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute outer product"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 2307989367
        n_calls = 191
        allocated_bytes = 7404803504

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute outer product".inner_timers]

        [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product"]
        total_time_ns = 398694752
        total_allocated_bytes = 933574896
        time_ns = 398694752
        n_calls = 191
        allocated_bytes = 933574896

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers."get submatrix"]
            total_time_ns = 0
            total_allocated_bytes = 0
            time_ns = 29984838
            n_calls = 191
            allocated_bytes = 55001088

                [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers."get submatrix".inner_timers]

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers."~compute matrix vector product~"]
            total_time_ns = 0
            total_allocated_bytes = 0
            time_ns = 1686803
            n_calls = 191
            allocated_bytes = 13119472

                [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers."~compute matrix vector product~".inner_timers]

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers.multiply]
            total_time_ns = 0
            total_allocated_bytes = 0
            time_ns = 367023111
            n_calls = 191
            allocated_bytes = 865454336

                [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers.multiply.inner_timers]

        [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."~compute E_Ω~"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 2592849
        n_calls = 191
        allocated_bytes = 6066016

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."~compute E_Ω~".inner_timers]
