total_time_ns = 141369853388
ksvd_pkg_rev = "7ba095a"
total_allocated_bytes = 32099712480
time_ns = 0
n_calls = 0
allocated_bytes = 0

[inner_timers.ksvd_update]
total_time_ns = 141369853388
total_allocated_bytes = 32099712480
time_ns = 141369853388
n_calls = 1
allocated_bytes = 32099712480

    [inner_timers.ksvd_update.inner_timers."compute and copy tsvd"]
    total_time_ns = 0
    total_allocated_bytes = 0
    time_ns = 92205689370
    n_calls = 3072
    allocated_bytes = 19336800320

        [inner_timers.ksvd_update.inner_timers."compute and copy tsvd".inner_timers]

    [inner_timers.ksvd_update.inner_timers."copy results"]
    total_time_ns = 4025180048
    total_allocated_bytes = 35224544
    time_ns = 4025180048
    n_calls = 24
    allocated_bytes = 35224544

        [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."~copy results~"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 152232
        n_calls = 24
        allocated_bytes = 1504

            [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."~copy results~".inner_timers]

        [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."copy D"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 2301111
        n_calls = 24
        allocated_bytes = 9216

            [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."copy D".inner_timers]

        [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."copy X"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 4022726705
        n_calls = 24
        allocated_bytes = 35213824

            [inner_timers.ksvd_update.inner_timers."copy results".inner_timers."copy X".inner_timers]

    [inner_timers.ksvd_update.inner_timers."find nonzeros"]
    total_time_ns = 0
    total_allocated_bytes = 0
    time_ns = 5965170195
    n_calls = 3072
    allocated_bytes = 56059200

        [inner_timers.ksvd_update.inner_timers."find nonzeros".inner_timers]

    [inner_timers.ksvd_update.inner_timers."maybe init bufers"]
    total_time_ns = 0
    total_allocated_bytes = 0
    time_ns = 5631
    n_calls = 1
    allocated_bytes = 16

        [inner_timers.ksvd_update.inner_timers."maybe init bufers".inner_timers]

    [inner_timers.ksvd_update.inner_timers."~ksvd_update~"]
    total_time_ns = 0
    total_allocated_bytes = 0
    time_ns = 65939392
    n_calls = 1
    allocated_bytes = 685632

        [inner_timers.ksvd_update.inner_timers."~ksvd_update~".inner_timers]

    [inner_timers.ksvd_update.inner_timers."copy X"]
    total_time_ns = 0
    total_allocated_bytes = 0
    time_ns = 68677945
    n_calls = 1
    allocated_bytes = 32825200

        [inner_timers.ksvd_update.inner_timers."copy X".inner_timers]

    [inner_timers.ksvd_update.inner_timers."compute E_Ω"]
    total_time_ns = 39039190807
    total_allocated_bytes = 12638117568
    time_ns = 39039190807
    n_calls = 3072
    allocated_bytes = 12638117568

        [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."copy data"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 1792620252
        n_calls = 3072
        allocated_bytes = 442368

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."copy data".inner_timers]

        [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute outer product"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 32454180405
        n_calls = 3072
        allocated_bytes = 12468123840

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute outer product".inner_timers]

        [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product"]
        total_time_ns = 4762829698
        total_allocated_bytes = 169416960
        time_ns = 4762829698
        n_calls = 3072
        allocated_bytes = 169416960

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers."get submatrix"]
            total_time_ns = 0
            total_allocated_bytes = 0
            time_ns = 121548582
            n_calls = 3072
            allocated_bytes = 169048832

                [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers."get submatrix".inner_timers]

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers."~compute matrix vector product~"]
            total_time_ns = 0
            total_allocated_bytes = 0
            time_ns = 14646307
            n_calls = 3072
            allocated_bytes = 122368

                [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers."~compute matrix vector product~".inner_timers]

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers.multiply]
            total_time_ns = 0
            total_allocated_bytes = 0
            time_ns = 4626634809
            n_calls = 3072
            allocated_bytes = 245760

                [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."compute matrix vector product".inner_timers.multiply.inner_timers]

        [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."~compute E_Ω~"]
        total_time_ns = 0
        total_allocated_bytes = 0
        time_ns = 29560452
        n_calls = 3072
        allocated_bytes = 134400

            [inner_timers.ksvd_update.inner_timers."compute E_Ω".inner_timers."~compute E_Ω~".inner_timers]
